### ISSUE TITLE
payment error 

### ISSUE THREAD

**Issue by hasu123** [vikas5914/woo-freecharge#1]
hello, i am using free charge plugin than i am selected sandbox method and go to the check out time using free charge option than time shoving error.[.](

![erro](https://cloud.githubusercontent.com/assets/20126125/18943045/b7331c32-863a-11e6-8fdd-0f6b5cef32d4.png)

**Comment by hasu123** [comment]
give me a testing id and secret key

**Comment by vikas5914** [comment]
test id and secret key is given by Freecharge .
